on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: seeeduino_xiao_ble
            shield: roBa_R
            snippet: studio-rpc-usb-uart
            artifact: roBa_R-seeeduino_xiao_ble-zmk
          - board: seeeduino_xiao_ble
            shield: roBa_L
            artifact: roBa_L-seeeduino_xiao_ble-zmk
          - board: seeeduino_xiao_ble
            shield: settings_reset
            artifact: settings_reset-seeeduino_xiao_ble-zmk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare build dir
        run: echo "build_dir=$(mktemp -d)" >> $GITHUB_ENV

      - name: Copy config to temp dir
        run: |
          mkdir -p /tmp/zmk-config/config
          cp -R config/* /tmp/zmk-config/config/

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            /tmp/zmk-config/modules/
            /tmp/zmk-config/tools/
            /tmp/zmk-config/zephyr/
            /tmp/zmk-config/bootloader/
            /tmp/zmk-config/zmk/
          key: ${{ runner.os }}-west-${{ hashFiles('**/west.yml') }}
          restore-keys: ${{ runner.os }}-west-

      - name: West Init
        working-directory: /tmp/zmk-config
        run: west init -l /tmp/zmk-config/config

      - name: West Update
        working-directory: /tmp/zmk-config
        run: west update --fetch-opt=--filter=tree:0

      - name: West Zephyr Export
        working-directory: /tmp/zmk-config
        run: west zephyr-export

      - name: Build ${{ matrix.shield }}
        working-directory: /tmp/zmk-config
        run: |
          west build -s zmk/app -d "${{ env.build_dir }}" -b "${{ matrix.board }}" \
            ${{ matrix.snippet != '' && format('-S "{0}"', matrix.snippet) || '' }} -- \
            -DZMK_CONFIG=/tmp/zmk-config/config \
            -DSHIELD="${{ matrix.shield }}" \
            -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}"

      - name: Upload ${{ matrix.shield }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ env.build_dir }}/zephyr/zmk.uf2
